language: node_js
node_js:
        - "0.11"
        - "0.10"
        - "0.8"
notifications:
    email: false
    irc:
        channels:
            - "irc.deltaanime.net#czechro"
        on_success: change
        on_failure: always